### PR TITLE
[IIIF-225] Resolve security warnings by deleting package-lock.json

### PR DESCRIPTION
**Pull request by hardyoyo**

### CODE REVIEW

**Comment by ksclarke** [comment]
In channel you were saying the package.json is not used (it's from an obsolete process). We should be able to remove package.json along with package-lock.json then right?

I'm trying to test by stepping through the README. I'm a yarn novice. When I run `yarn add universalviewer` per the README I get: `00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'add'`.

**Comment by hardyoyo** [comment]
I believe package.json is still required, just pack-lock.json is not, since we use yarn to download the dependencies, instead of npm.

**Comment by ksclarke** [comment]
Downloading from the Yarn site (instead of using what's in the OS package repo) works. Could we add that requirement to the README?

**Comment by ksclarke** [comment]
@hardyoyo After running the steps locally, my version of the yarn.lock file was updated. I've added those updates to this PR (along with a little more documentation for the README). Take a look over these additions.

**Comment by ksclarke** [comment]
After my update of yarn.lock, I still see one security issue:

kevin@kevin-laptop:~/Workspace/iiif-sandbox-simple$ yarn audit
yarn audit v1.16.0
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ bootbox                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mirador                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mirador > bootbox                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/882                         │
└───────────────┴──────────────────────────────────────────────────────────────┘
1 vulnerabilities found - Packages audited: 171
Severity: 1 Moderate

**Pull request merged**
